### ISSUE TITLE
Raw POST body

### ISSUE THREAD

**Issue by jeremejevs** [stvp/rollbar#19]
Can you, please, include raw POST body (`data.request.body`) into request-related Occurrences, as per [the spec](https://rollbar.com/docs/api/items_post/)? Or is it omitted intentionally (i.e. for field filtering)? It's a problem for me, because all my POST requests are sent as JSON and not form-urlencoded, so I can't see what goes wrong in the dashboard.

Let me know if you don't have time for this, I'll try patching this myself then (but would prefer not to, since I'm relatively new to Go).

**Comment by tysontate** [comment]
It's omitted because we simply didn't have a need to record request bodies in Rollbar. In a pinch, you can add request bodies using a custom field:

```
body, err := ioutil.ReadAll(request.Body)
defer request.Body.Close()
...
rollbar.RequestError(rollbar.ERR, request, error, rollbar.Field{"body", body})
```

Otherwise, I'm open to any and all Pull Requests! :)
