### ISSUE TITLE
Is there a way to ask Rollbar to print the errors in 'stderr' as well?

### ISSUE THREAD

**Issue by corgrath** [stvp/rollbar#25]
Maybe this already exists, or maybe its a feature request, but is there a way to tell Rollbar to print errors, warnings, etc to `stderr` as well as positing it to the remote server?

Would be a nice handy feature to have for us developers for who wants to see errors both locally but also on the web automatically, by using a single logging logic in our code.

**Comment by tysontate** [comment]
@corgrath This sounds useful. What kind of format would you expect to see from `stvp/rollbar` when printing errors to stderr? Is there a standard format that you're aware of or should it just be a pretty-printed version of the input params?

**Comment by bpo** [comment]
Just popping in here to offer an alternative view: the approach @corgrath outlines is a best practice in principal, but it doesn't feel rollbar-specific and therefore probably isn't the best thing for this go library.

While the lowest common denominator for fallback might be to print to stderr, there are plenty of reasons you might want to do something else first (write to another io channel, invoke some secondary error-handling library, etc). So you'd also at least need a new configuration option to turn this new feature on and off. And then the rabbit hole is opened up for configuring which pipes to send the data down, formatting tweaks, exponential backoff, and more.

A simple client library steps toward the complication of "log frameworks" this way. Perhaps showing how to reliably wrap/extend the `rollbar` client with a fallback channel to could be better demonstrated in a wiki doc?

-My 2cents.

**Comment by corgrath** [comment]
If there is a philosophical obstacle here (as in "what is actual useful for developers of this library vs what my opinions are regarding single responsibility and separation of concerns for this library"), having this as as a debug feature (enabled by a debug flag) would mitigate that obstacle, since it is common that libraries prints debug data to the console. 

Meaning, this library could also print out the given data to the stderr/stadout directly - for debugging purposes of course, for developers who wants to see what the library got and is sending to the server.

This approach would still help to push for this feature request, while being aligned to philosophical concern.

**Comment by bpo** [comment]
@corgrath sorry for the late reply here. Open to a PR for the debug flag that you suggested – it seems completely reasonable. 👍
