### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by marcelgruber** [stvp/rollbar#26]
Hello. I think it would be worthwhile including a guide or a link to a guide in the readme. I'm just starting in the GoLang game and this would be helpful. If you provide guidance I can make the change request on the README file as I personally go through the process. Cheers.

**Comment by bpo** [comment]
Hey there. Installing should just be a matter of putting it in your GOPATH. You can do that automatically with the go tool by running `go get github.com/stvp/rollbar` – then you make calls to it via a standard import statement.

Documentation patches would be great!

**Comment by marcelgruber** [comment]
Thanks for the guidance! Feel free to edit my changes.
