### ISSUE TITLE
would be cool to have updated releases

### ISSUE THREAD

**Issue by dfuentes77** [stvp/rollbar#32]
Last one was 2015.

Don't want to always pull from master.

For example, using glide, would like to only pull certain patch/minor versions based on our comfort.

**Comment by bpo** [comment]
@dfuentes77 patches for release bumps would be happily accepted.

**Comment by bpo** [comment]
Just to provide some more detail here – @stvp no longer uses this package. I'm happy to continue to review and merge patches as they come in. If a version bump seems in order, just issue a PR noting the details and I will merge and tag.

**Comment by dfuentes77** [comment]
@bpo done: https://github.com/stvp/rollbar/pull/33

Thanks!
