### ISSUE TITLE
Rollbar error: received response: 429 Too Many Requests

### ISSUE THREAD

**Issue by maxcnunes** [stvp/rollbar#40]
The service I working on sends errors to rollbar from a logrus hook and when there are a lot of errors I see this failure coming from Rollbar client:
```
Rollbar error: received response: 429 Too Many Requests
```
Is there a way to mitigate this issue?

**Comment by bpo** [comment]
@maxcnunes you probably want to take a look at https://docs.rollbar.com/docs/rate-limits and see about increasing the limit for your service. Otherwise you would need to find a way to rate-limit yourself client-side, not something that this library can help you with.
