### ISSUE TITLE
Use actual error class name for default error type

### ISSUE THREAD

**Issue by waltjones** [stvp/rollbar#42]
Would you consider updating how class names are reported for "errors.errorString", or would you take a PR for this?

The Rollbar grouping team has made improvements to error grouping, however hashing the class name based on the message string causes grouping to fail. Any difference in the message string looks like a new error class. 

This PR makes the recommended change in the rollbar-go package:
https://github.com/rollbar/rollbar-go/pull/60

Related to the stvp/rollbar code here:
https://github.com/stvp/rollbar/blob/master/rollbar.go#L333-L335

**Comment by bpo** [comment]
Hey there, yep, would happily accept a PR for this. Rollbar has added many improvements that aren't reflected in this client yet.

**Comment by waltjones** [comment]
Great, thank you. I'll get a PR ready.

**Comment by bpo** [comment]
Thanks for the patch!
